name: scan_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  shared_preferences: ^2.0.15
  photo_view: ^0.14.0
  provider: ^6.0.5
  http: ^1.2.1
  email_auth: ^2.0.0
  mailer: 6.3.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
